### PR TITLE
Remove Outdated Link

### PR DESCRIPTION
**Pull request by dargmuesli**
Something tells me that this link isn't what it was anymore.

### CODE REVIEW

**Comment by dargmuesli** [comment]
Seems like I forgot to open this PR three months ago 😅

**Comment by marvinroger** [comment]
Ahah, thanks. 😄

**Comment by marvinroger** [comment]
These free `.tk` domains are indeed kind of... Surprising?

**Comment by dargmuesli** [comment]
Well if the current content on that domain surprises you, I better don't tell you that three months ago it led to a standard pr0n site, do I? :D

**Comment by marvinroger** [comment]
Yeah, I noticed that, I just forgot to remove the link and I thought this was still pointing to that site!

**Pull request merged**
